//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriathlonResults.Central.ServiceRequests.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Xml.Serialization;
using System.Runtime.InteropServices;

    [Guid("4FB58A9A-2296-4c31-9CB4-C6EF82913C57")]
    [ComDefaultInterface(typeof(IRecordResultResponse))]
    [Serializable()]
    [XmlRoot(ElementName = "RecordResultResponse", Namespace = "http://TriathlonResults.Central.Schemas/1.0/")]
    public partial class RecordResultResponse : IRecordResultResponse
    {

        private bool _recordResultResult;

        public RecordResultResponse()
        {
        }

        public virtual bool RecordResultResult
        {
            get
            {
                return _recordResultResult;
            }
            set
            {
                _recordResultResult = value;
            }
        }
    }

    [Guid("2D3A6730-2EE0-4c45-9EB7-6D25F291DFF8")]
    public interface IRecordResultResponse
    {
        bool RecordResultResult { get; set;}
    }
}
