//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriathlonResults.Central.ServiceRequests.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Xml.Serialization;
    using System.Runtime.InteropServices;

    [Guid("9D51569D-D95E-4e1b-94FE-E18D1F62ED36")]
    [ComDefaultInterface(typeof(IRecordResultRequest))]
    [Serializable()]
    [XmlRoot(ElementName = "RecordResult", Namespace = "http://TriathlonResults.Central.Schemas/1.0/")]
    public partial class RecordResultRequest : IRecordResultRequest
    {

        private SectorTime _result;

        public RecordResultRequest()
        {
        }

        public virtual SectorTime result
        {
            get
            {
                return _result;
            }
            set
            {
                _result = value;
            }
        }
    }

    [Guid("9801D8C7-05EC-4c06-BC8F-64C2FBEFF1C3")]
    public interface IRecordResultRequest
    {
        SectorTime result { get; set;}
    }
}
