//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriathlonResults.Central.ServiceRequests
{
    using ESBSimpleSamples.ServiceClient.Itineraries;
    using ESBSimpleSamples.ServiceClient.ServiceRequests;
    using System;
    using System.Collections.Generic;
    using System.Text;
    using TriathlonResults.Central.ServiceRequests.Entities;
using System.Runtime.InteropServices;

    [Guid("75E94410-74BE-41ba-AF8A-DD538D73639B")]
    [ClassInterface(ClassInterfaceType.None)]
    [ComDefaultInterface(typeof(IRecordResult))]
    public partial class RecordResult : ESBServiceRequest<RecordResultRequest, RecordResultResponse>, IRecordResult
    {

        public RecordResult()
        {
        }

        public override ItineraryRequest PrepareRequest()
        {
            ItineraryBuilder builder = new ItineraryBuilder();
            builder.AddRoutingService("TriathlonResults", "RecordResult");
            builder.AddRequestResponseService();
            ItineraryRequest request = new ItineraryRequest();
            request.Header = builder.GetItinerary();
            request.Body = this.GetRequestBody();
            return request;
        }
    }

    [Guid("257421E3-1394-43fb-9FB1-3BE72A486B45")]
    public interface IRecordResult
    {
        RecordResultRequest Request { get; set;}
        RecordResultResponse Response { get; set;}
    }
}
