//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.CarValet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Make
    {
        public Make()
        {
            this.Models = new HashSet<Model>();
        }
    
        public string MakeCode { get; set; }
        public string MakeName { get; set; }
        public string MakeNameLower { get; set; }
    
        public virtual ICollection<Model> Models { get; set; }
    }
}
