//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.CarValet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public string MakeCode { get; set; }
        public string ModelCode { get; set; }
        public string ModelName { get; set; }
        public string ModelNameLower { get; set; }
    
        public virtual Make Make { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
