//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sixeyed.CarValet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleId { get; set; }
        public System.DateTime ProducedFromUtc { get; set; }
        public Nullable<System.DateTime> ProducedToUtc { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
