//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleClient.SampleService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleClient.SampleService.IErroringService")]
    public interface IErroringService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErroringService/ThrowUnhandledException", ReplyAction="http://tempuri.org/IErroringService/ThrowUnhandledExceptionResponse")]
        void ThrowUnhandledException();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IErroringService/LogHandledException", ReplyAction="http://tempuri.org/IErroringService/LogHandledExceptionResponse")]
        void LogHandledException();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IErroringServiceChannel : SampleClient.SampleService.IErroringService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ErroringServiceClient : System.ServiceModel.ClientBase<SampleClient.SampleService.IErroringService>, SampleClient.SampleService.IErroringService
    {
        
        public ErroringServiceClient()
        {
        }
        
        public ErroringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ErroringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ErroringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ErroringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void ThrowUnhandledException()
        {
            base.Channel.ThrowUnhandledException();
        }
        
        public void LogHandledException()
        {
            base.Channel.LogHandledException();
        }
    }
}
