//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace Microsoft.Practices.ESB
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;

    #region Fault - Submit

    namespace ExceptionManagement
    {

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Web.Services.WebServiceBindingAttribute(Name = "ExceptionHandlingSoap", Namespace = "http://microsoft.biztalk.practices.esb.com/exceptionhandling/")]
        public partial class ExceptionHandling : System.Web.Services.Protocols.SoapHttpClientProtocol
        {

            private System.Threading.SendOrPostCallback SubmitFaultOperationCompleted;

            private bool useDefaultCredentialsSetExplicitly;

            /// <remarks/>
            public ExceptionHandling()
            {
                this.Url = "http://localhost/esb.exceptionhandlingservices/exceptionhandling.asmx";
                if ((this.IsLocalFileSystemWebService(this.Url) == true))
                {
                    this.UseDefaultCredentials = true;
                    this.useDefaultCredentialsSetExplicitly = false;
                }
                else
                {
                    this.useDefaultCredentialsSetExplicitly = true;
                }
            }

            public new string Url
            {
                get
                {
                    return base.Url;
                }
                set
                {
                    if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                                && (this.useDefaultCredentialsSetExplicitly == false))
                                && (this.IsLocalFileSystemWebService(value) == false)))
                    {
                        base.UseDefaultCredentials = false;
                    }
                    base.Url = value;
                }
            }

            public new bool UseDefaultCredentials
            {
                get
                {
                    return base.UseDefaultCredentials;
                }
                set
                {
                    base.UseDefaultCredentials = value;
                    this.useDefaultCredentialsSetExplicitly = true;
                }
            }

            /// <remarks/>
            public event SubmitFaultCompletedEventHandler SubmitFaultCompleted;

            /// <remarks/>
            [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.biztalk.practices.esb.com/exceptionhandling/ExceptionHandling/Su" +
                "bmitFault", RequestNamespace = "http://microsoft.biztalk.practices.esb.com/exceptionhandling/", OneWay = true, Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
            public void SubmitFault([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/exceptionhandling")] FaultMessage FaultMessage)
            {
                this.Invoke("SubmitFault", new object[] {
                        FaultMessage});
            }

            /// <remarks/>
            public void SubmitFaultAsync(FaultMessage FaultMessage)
            {
                this.SubmitFaultAsync(FaultMessage, null);
            }

            /// <remarks/>
            public void SubmitFaultAsync(FaultMessage FaultMessage, object userState)
            {
                if ((this.SubmitFaultOperationCompleted == null))
                {
                    this.SubmitFaultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitFaultOperationCompleted);
                }
                this.InvokeAsync("SubmitFault", new object[] {
                        FaultMessage}, this.SubmitFaultOperationCompleted, userState);
            }

            private void OnSubmitFaultOperationCompleted(object arg)
            {
                if ((this.SubmitFaultCompleted != null))
                {
                    System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                    this.SubmitFaultCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
                }
            }

            /// <remarks/>
            public new void CancelAsync(object userState)
            {
                base.CancelAsync(userState);
            }

            private bool IsLocalFileSystemWebService(string url)
            {
                if (((url == null)
                            || (url == string.Empty)))
                {
                    return false;
                }
                System.Uri wsUri = new System.Uri(url);
                if (((wsUri.Port >= 1024)
                            && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
                {
                    return true;
                }
                return false;
            }
        }
        /// <remarks/>
        // http://schemas.microsoft.biztalk.practices.esb.com/exceptionhandling#FaultMessage --> FaultMessage
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BTSWebSvcWiz", "3.0.1.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.biztalk.practices.esb.com/exceptionhandling", IsNullable = false)]
        public partial class FaultMessage
        {

            private FaultMessageHeader headerField;

            private FaultMessageExceptionObject exceptionObjectField;

            private FaultMessageMessage[] messagesField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public FaultMessageHeader Header
            {
                get
                {
                    return this.headerField;
                }
                set
                {
                    this.headerField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public FaultMessageExceptionObject ExceptionObject
            {
                get
                {
                    return this.exceptionObjectField;
                }
                set
                {
                    this.exceptionObjectField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            [System.Xml.Serialization.XmlArrayItemAttribute("Message", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
            public FaultMessageMessage[] Messages
            {
                get
                {
                    return this.messagesField;
                }
                set
                {
                    this.messagesField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BTSWebSvcWiz", "3.0.1.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class FaultMessageHeader
        {

            private string applicationField;

            private string descriptionField;

            private string errorTypeField;

            private string failureCategoryField;

            private string faultCodeField;

            private string faultDescriptionField;

            private int faultSeverityField;

            private string scopeField;

            private string serviceInstanceIDField;

            private string serviceNameField;

            private string faultGeneratorField;

            private string machineNameField;

            private string dateTimeField;

            private string controlBitField;

            private string messageIDField;

            private string activityIdentityField;

            private bool nACKField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Application
            {
                get
                {
                    return this.applicationField;
                }
                set
                {
                    this.applicationField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Description
            {
                get
                {
                    return this.descriptionField;
                }
                set
                {
                    this.descriptionField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ErrorType
            {
                get
                {
                    return this.errorTypeField;
                }
                set
                {
                    this.errorTypeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string FailureCategory
            {
                get
                {
                    return this.failureCategoryField;
                }
                set
                {
                    this.failureCategoryField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string FaultCode
            {
                get
                {
                    return this.faultCodeField;
                }
                set
                {
                    this.faultCodeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string FaultDescription
            {
                get
                {
                    return this.faultDescriptionField;
                }
                set
                {
                    this.faultDescriptionField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public int FaultSeverity
            {
                get
                {
                    return this.faultSeverityField;
                }
                set
                {
                    this.faultSeverityField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Scope
            {
                get
                {
                    return this.scopeField;
                }
                set
                {
                    this.scopeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ServiceInstanceID
            {
                get
                {
                    return this.serviceInstanceIDField;
                }
                set
                {
                    this.serviceInstanceIDField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ServiceName
            {
                get
                {
                    return this.serviceNameField;
                }
                set
                {
                    this.serviceNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string FaultGenerator
            {
                get
                {
                    return this.faultGeneratorField;
                }
                set
                {
                    this.faultGeneratorField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string MachineName
            {
                get
                {
                    return this.machineNameField;
                }
                set
                {
                    this.machineNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string DateTime
            {
                get
                {
                    return this.dateTimeField;
                }
                set
                {
                    this.dateTimeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ControlBit
            {
                get
                {
                    return this.controlBitField;
                }
                set
                {
                    this.controlBitField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string MessageID
            {
                get
                {
                    return this.messageIDField;
                }
                set
                {
                    this.messageIDField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ActivityIdentity
            {
                get
                {
                    return this.activityIdentityField;
                }
                set
                {
                    this.activityIdentityField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public bool NACK
            {
                get
                {
                    return this.nACKField;
                }
                set
                {
                    this.nACKField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BTSWebSvcWiz", "3.0.1.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class FaultMessageExceptionObject
        {

            private string messageField;

            private string typeField;

            private string sourceField;

            private string targetSiteField;

            private string stackTraceField;

            private string innerExceptionMessageField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Message
            {
                get
                {
                    return this.messageField;
                }
                set
                {
                    this.messageField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Type
            {
                get
                {
                    return this.typeField;
                }
                set
                {
                    this.typeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Source
            {
                get
                {
                    return this.sourceField;
                }
                set
                {
                    this.sourceField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string TargetSite
            {
                get
                {
                    return this.targetSiteField;
                }
                set
                {
                    this.targetSiteField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string StackTrace
            {
                get
                {
                    return this.stackTraceField;
                }
                set
                {
                    this.stackTraceField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string InnerExceptionMessage
            {
                get
                {
                    return this.innerExceptionMessageField;
                }
                set
                {
                    this.innerExceptionMessageField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BTSWebSvcWiz", "3.0.1.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class FaultMessageMessage
        {

            private string contentTypeField;

            private string messageNameField;

            private string routingURLField;

            private FaultMessageMessageContextProperty[] messageContextField;

            private string messageIDField;

            private string interchangeIDField;

            private string messageTypeField;

            private FaultMessageMessageMessageData messageDataField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string ContentType
            {
                get
                {
                    return this.contentTypeField;
                }
                set
                {
                    this.contentTypeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string MessageName
            {
                get
                {
                    return this.messageNameField;
                }
                set
                {
                    this.messageNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string RoutingURL
            {
                get
                {
                    return this.routingURLField;
                }
                set
                {
                    this.routingURLField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            [System.Xml.Serialization.XmlArrayItemAttribute("ContextProperty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
            public FaultMessageMessageContextProperty[] MessageContext
            {
                get
                {
                    return this.messageContextField;
                }
                set
                {
                    this.messageContextField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string MessageID
            {
                get
                {
                    return this.messageIDField;
                }
                set
                {
                    this.messageIDField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string InterchangeID
            {
                get
                {
                    return this.interchangeIDField;
                }
                set
                {
                    this.interchangeIDField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string MessageType
            {
                get
                {
                    return this.messageTypeField;
                }
                set
                {
                    this.messageTypeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public FaultMessageMessageMessageData MessageData
            {
                get
                {
                    return this.messageDataField;
                }
                set
                {
                    this.messageDataField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BTSWebSvcWiz", "3.0.1.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class FaultMessageMessageContextProperty
        {

            private string nameField;

            private string valueField;

            private string typeField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Type
            {
                get
                {
                    return this.typeField;
                }
                set
                {
                    this.typeField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BTSWebSvcWiz", "3.0.1.0")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class FaultMessageMessageMessageData
        {

            private System.Xml.XmlNode[] anyField;

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            [System.Xml.Serialization.XmlAnyElementAttribute()]
            public System.Xml.XmlNode[] Any
            {
                get
                {
                    return this.anyField;
                }
                set
                {
                    this.anyField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
        public delegate void SubmitFaultCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    }

    #endregion
}

#pragma warning restore 1591