//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPersonalizationSample.ServiceClient.PersonalizationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindStateResult", Namespace="http://schemas.datacontract.org/2004/07/WcfPersonalizationProvider")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<WcfPersonalizationSample.ServiceClient.PersonalizationService.PersonalizationStateInfoCollectionKey, int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Web.UI.WebControls.WebParts.PersonalizationStateQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Web.UI.WebControls.WebParts.PersonalizationScope))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPersonalizationSample.ServiceClient.PersonalizationService.PersonalizationStateInfoCollectionKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Web.UI.WebControls.WebParts.SharedPersonalizationStateInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Web.UI.WebControls.WebParts.PersonalizationStateInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Web.UI.WebControls.WebParts.UserPersonalizationStateInfo))]
    public partial class FindStateResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Web.UI.WebControls.WebParts.PersonalizationStateInfoCollection StateInfoCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Web.UI.WebControls.WebParts.PersonalizationStateInfoCollection StateInfoCollection {
            get {
                return this.StateInfoCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.StateInfoCollectionField, value) != true)) {
                    this.StateInfoCollectionField = value;
                    this.RaisePropertyChanged("StateInfoCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalizationStateInfoCollection.Key", Namespace="http://schemas.datacontract.org/2004/07/System.Web.UI.WebControls.WebParts")]
    [System.SerializableAttribute()]
    public partial class PersonalizationStateInfoCollectionKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PathField;
        
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonalizationService.IPersonalizationService")]
    public interface IPersonalizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalizationService/FindState", ReplyAction="http://tempuri.org/IPersonalizationService/FindStateResponse")]
        WcfPersonalizationSample.ServiceClient.PersonalizationService.FindStateResult FindState(System.Web.UI.WebControls.WebParts.PersonalizationScope scope, System.Web.UI.WebControls.WebParts.PersonalizationStateQuery query, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalizationService/GetCountOfState", ReplyAction="http://tempuri.org/IPersonalizationService/GetCountOfStateResponse")]
        int GetCountOfState(System.Web.UI.WebControls.WebParts.PersonalizationScope scope, System.Web.UI.WebControls.WebParts.PersonalizationStateQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalizationService/GetSharedPersonalizationBlob", ReplyAction="http://tempuri.org/IPersonalizationService/GetSharedPersonalizationBlobResponse")]
        byte[] GetSharedPersonalizationBlob(string path, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalizationService/GetUserPersonalizationBlob", ReplyAction="http://tempuri.org/IPersonalizationService/GetUserPersonalizationBlobResponse")]
        byte[] GetUserPersonalizationBlob(string path, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalizationService/ResetPersonalizationBlob", ReplyAction="http://tempuri.org/IPersonalizationService/ResetPersonalizationBlobResponse")]
        void ResetPersonalizationBlob(string path, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalizationService/ResetState", ReplyAction="http://tempuri.org/IPersonalizationService/ResetStateResponse")]
        int ResetState(System.Web.UI.WebControls.WebParts.PersonalizationScope scope, string[] paths, string[] usernames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalizationService/ResetUserState", ReplyAction="http://tempuri.org/IPersonalizationService/ResetUserStateResponse")]
        int ResetUserState(string path, System.DateTime userInactiveSinceDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalizationService/SavePersonalizationBlob", ReplyAction="http://tempuri.org/IPersonalizationService/SavePersonalizationBlobResponse")]
        void SavePersonalizationBlob(string path, string userName, byte[] dataBlob);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPersonalizationServiceChannel : WcfPersonalizationSample.ServiceClient.PersonalizationService.IPersonalizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PersonalizationServiceClient : System.ServiceModel.ClientBase<WcfPersonalizationSample.ServiceClient.PersonalizationService.IPersonalizationService>, WcfPersonalizationSample.ServiceClient.PersonalizationService.IPersonalizationService {
        
        public PersonalizationServiceClient() {
        }
        
        public PersonalizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonalizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfPersonalizationSample.ServiceClient.PersonalizationService.FindStateResult FindState(System.Web.UI.WebControls.WebParts.PersonalizationScope scope, System.Web.UI.WebControls.WebParts.PersonalizationStateQuery query, int pageIndex, int pageSize) {
            return base.Channel.FindState(scope, query, pageIndex, pageSize);
        }
        
        public int GetCountOfState(System.Web.UI.WebControls.WebParts.PersonalizationScope scope, System.Web.UI.WebControls.WebParts.PersonalizationStateQuery query) {
            return base.Channel.GetCountOfState(scope, query);
        }
        
        public byte[] GetSharedPersonalizationBlob(string path, string userName) {
            return base.Channel.GetSharedPersonalizationBlob(path, userName);
        }
        
        public byte[] GetUserPersonalizationBlob(string path, string userName) {
            return base.Channel.GetUserPersonalizationBlob(path, userName);
        }
        
        public void ResetPersonalizationBlob(string path, string userName) {
            base.Channel.ResetPersonalizationBlob(path, userName);
        }
        
        public int ResetState(System.Web.UI.WebControls.WebParts.PersonalizationScope scope, string[] paths, string[] usernames) {
            return base.Channel.ResetState(scope, paths, usernames);
        }
        
        public int ResetUserState(string path, System.DateTime userInactiveSinceDate) {
            return base.Channel.ResetUserState(path, userInactiveSinceDate);
        }
        
        public void SavePersonalizationBlob(string path, string userName, byte[] dataBlob) {
            base.Channel.SavePersonalizationBlob(path, userName, dataBlob);
        }
    }
}
